### ISSUE TITLE
Crashes on missing files in anonymized repo

### ISSUE THREAD

**Issue by gwern** [ShoufaChen/clone-anonymous4open#3]
I can run successfully the provided example, but in trying the [repo of interest to me](https://anonymous.4open.science/r/5c1049ba-109f-4a12-9d74-9a4a5130ce97/), it crashes on

https://anonymous.4open.science/repository/5c1049ba-109f-4a12-9d74-9a4a5130ce97/IN256_imgs.npz

That file has no `<code>` element or otherwise, and is an error page:

>  The file IN256_imgs.npz is too big to be anonymized (beyond 1MB, Github limit)

Probably it should just skip such files?

~~~{.Diff}
diff clone.py clone-fixed.py                                                                                                                                                                    
61c61,64
<             f.write(source_code.get_text())
---
>             try:
>                 f.write(source_code.get_text())
>             except:
>                 print("Err: %s" % file_name)
~~~

**Comment by ShoufaChen** [comment]
Thanks very much for pointing out this problem.

Add a temporary workaround at https://github.com/ShoufaChen/clone-anonymous4open/commit/0ceb4ac607ed38d5bf5e3d49efed7d748b919f97
