### ISSUE TITLE
Does not clone README.md

### ISSUE THREAD

**Issue by nslay** [ShoufaChen/clone-anonymous4open#5]
I noticed that this tool does not actually clone the README.md file (it says it does, but it doesn't). My long ago submitted zipfile of my anonymized sources are without documentation...

Hopefully reviewers will follow the anonymous.4open.science footnote in the paper itself! That will have all the documentation!

Thank you for developing this tool!

**Comment by ShoufaChen** [comment]
Hi, @nslay 

You're welcome.
In fact the `README.md`is **TODO work**. 

But as this repo does not be used by many people, I do not have a plan to improve it.

Welcome to your PR.
